name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-pdf:
    name: build-pdf
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v3
      with:
        root_file: r2cheatsheet.tex
    - name: Upload PDF file
      uses: actions/upload-artifact@v3
      with:
        name: PDF
        path: r2cheatsheet.pdf
