name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-r2-pdf:
    name: build-r2-pdf
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v3
      with:
        root_file: r2cheatsheet.tex
    - name: Upload PDF file
      uses: actions/upload-artifact@v4
      with:
        name: PDF
        path: r2cheatsheet.pdf
  build-r2frida-pdf:
    name: build-r2frida-pdf
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v3
      with:
        root_file: r2frida_cheatsheet.tex
    - name: Upload PDF file
      uses: actions/upload-artifact@v4
      with:
        name: PDF
        path: r2frida_cheatsheet.pdf
